## STATIC CONFIGURATION
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/certs/fullchain.pem"
      keyFile: "/certs/privkey.pem"
      stores:
        - default
