## STATIC CONFIGURATION
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    tls:
      certificates:
        certFile: /certs/fullchain.pem
        keyFile: /certs/privkey.pem

providers:
  docker:
    exposedByDefault: false
